CREATE DATABASE IF NOT EXISTS halo_social CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE halo_social;

CREATE TABLE IF NOT EXISTS tweets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  author VARCHAR(80) NOT NULL,
  handle VARCHAR(80) NOT NULL,
  content VARCHAR(280) NOT NULL,
  likes INT NOT NULL DEFAULT 0,
  comments INT NOT NULL DEFAULT 0,
  retweets INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tweet_id BIGINT UNSIGNED NOT NULL,
  author VARCHAR(80) NOT NULL,
  handle VARCHAR(80) NOT NULL,
  content VARCHAR(280) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_comments_tweet FOREIGN KEY (tweet_id) REFERENCES tweets(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
